### ISSUE TITLE
OEM Code not found!

### ISSUE THREAD

**Issue by bagou4502** [SkyEmie/huawei-honor-unlock-bootloader#61]
Hello i try all code but i have OEM Code not found!

What is the problem?
(STF-L09C432)

**Comment by rauldux** [comment]
Problem is that, if i've got my math right here and asume a european version (with only decimal numbers in use), there are 10^16 combinations which are 10 billiards of possibilities. because most devices have brutforce protection and this script works around this rebooting every 4 atemps let's say for simplification one try of combinations takes 1 second. This would then be 321502057.6 years to try all possible combinations. What this script does is trying random numbers. Which brings us to your question, the possibility of not finding the correct combination is relatively high. 
Taking into account alphnumerics non case-sensitiv it would be 10^36

**Comment by deniscaraus** [comment]
> 
> 
> Problem is that, if i've got my math right here and asume a european version (with only decimal numbers in use), there are 10^16 combinations which are 10 billiards of possibilities. because most devices have brutforce protection and this script works around this rebooting every 4 atemps let's say for simplification one try of combinations takes 1 second. This would then be 321502057.6 years to try all possible combinations. What this script does is trying random numbers. Which brings us to your question, the possibility of not finding the correct combination is relatively high.

No, this script doesn't seem to try random numbers. From what i can see, it takes a base of 10^15 and increments it by the IMEI's square root times 1024 until it reaches a number greater than 10^16.

**Comment by rauldux** [comment]
agree, let's say not totally random, as the creator of the script said here:
https://github.com/SkyEmie/huawei-honor-unlock-bootloader/issues/54#issue-679514583

**Comment by Manki9000** [comment]
I got the same OEM Code not found error on my Huawei P10 Lite.

**Comment by lcapriotti** [comment]
same with me with EU Honor 5C

**Comment by Fijxu** [comment]
I couldn't find the code, what's the difference between the EU and AMERICA version, is there a way to adapt this code for AMERICAN phones?

I tried in my CAM-L03 and I didn't find anything

If it is possible to adapt the code to make a version of AMERICA I can help
